import Header from'./Header'
import Footer from './Footer'
import Banner from './Banner'
import Homepage from '../pages/Homepage'
import Category from './Category'
import Cart from '../pages/Cart'
import Order from './Order'
import CustomerSignUp from '../pages/CustomerSignUp'
import CustomerLogin from '../pages/CustomerLogin'
import ProductCard from './ProductCard'
import Checkout from '../pages/Checkout'
import UpdatePassword from '../pages/UpdatePassword'
import Account from '../pages/Account'
import AccountContent from '../pages/AccountContent'
import OrderPage from '../pages/OrderPage'
import BottomNavbar from './BottomNavbar'
import Shop from '../pages/Shop'
import SearchPage from '../pages/SearchPage'
import Error from '../pages/Error'
import ShippingPolicy from './ShippingPolicy'
import ReturnPolicy from './ReturnPolicy'
import AboutUs from '../pages/AboutUs'
import QuickCheckout from '../pages/QuickCheckout'
import PaymentResponsePage from '../pages/PaymentResponsePage'

export { Header, Footer, Banner, Homepage, Shop, QuickCheckout, PaymentResponsePage, BottomNavbar, ProductCard, SearchPage, CustomerSignUp, CustomerLogin, Error, Category, Cart, ReturnPolicy, ShippingPolicy, AboutUs, Order, OrderPage, AccountContent, UpdatePassword, Checkout, Account }